#!/usr/bin/env bash

DURATION="${WAITING_FOR_FPM_SERVICE_IN_SEC:-30}"

COUNTER=1
while [  $COUNTER -le $DURATION ]; do
   # check php-fpm - result 0 means it is all ok and we may start nginx
   FCGI_CONNECT=/var/run/php-fpm.sock php-fpm-healthcheck
   RES=$?
   echo "$RES"
   if [ $RES -eq 0 ]
   then
     echo "PHP-FPM is ok. Nginx is starting..."
     exec nginx -g "daemon off;"
   fi
   echo "Waiting in seconds: $COUNTER"
   let COUNTER=COUNTER+1
   sleep 1
done

# if php-fpm service has not started
echo "PHP-FPM starting timeout error...have to bring down all services in the container"
s6-svscanctl -t /var/run/s6/services
